#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/Relight.jar:$APPDIR/lib/core.jar:$APPDIR/lib/mtj.jar:$APPDIR/lib/blas.jar:$APPDIR/lib/arpack_combined_all.jar:$APPDIR/lib/netlib-java-0.9.1.jar:$APPDIR/lib/arpack_combo-0.1.jar:$APPDIR/lib/ini4j.jar" Relight
